/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 book.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Book(props) {
  const { nodes, materials } = useGLTF('/book.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Book_Cover-Cover'].geometry} material={materials['Book Cover-Cover']} position={[0.022, 0.498, -0.001]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.EPG_cover.geometry} material={materials['EPG cover']} position={[-0.022, 0.498, -0.001]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Book Inner']} position={[0, 0.543, 0.003]} scale={[0.038, 0.543, 0.543]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[0, 0.498, 0.39]} scale={[0.038, 0.543, 0.543]} />
    </group>
  )
}

useGLTF.preload('/book.glb')
